package com.fuguo.form;

import java.io.Serializable;
import java.util.Date;

import org.apache.struts.action.ActionForm;

import bsw.base.BaseDTO;



/**
 * User generated by MyEclipse - Hibernate Tools
 */

public class SunForm    extends ActionForm  {


	private Integer id;
    private String timeid;
    private String bdz;
    private String sblx;
    private String sbmc;
    private String dydj;
    private String gzqxxx;
    private String clgc;
    private String fssj;
    private String clsj;
    private Integer ts;
    private String fxr;
    private String hbr;
    private String qxr;
    private String ysr;
    private String tbr;
    private String banzu;
    private String bz;
    private String jhzt;
    private String flag1;
    private String flag2;
    private String flag3;
    private String flag4;
    private String flag5;
    private String flag6;
    private String flag7;
    private String flag8;
    private String flag9;
    private String flag10;
	public String getBanzu() {
		return banzu;
	}
	public void setBanzu(String banzu) {
		this.banzu = banzu;
	}
	public String getBdz() {
		return bdz;
	}
	public void setBdz(String bdz) {
		this.bdz = bdz;
	}
	public String getBz() {
		return bz;
	}
	public void setBz(String bz) {
		this.bz = bz;
	}
	public String getClgc() {
		return clgc;
	}
	public void setClgc(String clgc) {
		this.clgc = clgc;
	}
	public String getClsj() {
		return clsj;
	}
	public void setClsj(String clsj) {
		this.clsj = clsj;
	}
	public String getDydj() {
		return dydj;
	}
	public void setDydj(String dydj) {
		this.dydj = dydj;
	}
	public String getFlag1() {
		return flag1;
	}
	public void setFlag1(String flag1) {
		this.flag1 = flag1;
	}
	public String getFlag10() {
		return flag10;
	}
	public void setFlag10(String flag10) {
		this.flag10 = flag10;
	}
	public String getFlag2() {
		return flag2;
	}
	public void setFlag2(String flag2) {
		this.flag2 = flag2;
	}
	public String getFlag3() {
		return flag3;
	}
	public void setFlag3(String flag3) {
		this.flag3 = flag3;
	}
	public String getFlag4() {
		return flag4;
	}
	public void setFlag4(String flag4) {
		this.flag4 = flag4;
	}
	public String getFlag5() {
		return flag5;
	}
	public void setFlag5(String flag5) {
		this.flag5 = flag5;
	}
	public String getFlag6() {
		return flag6;
	}
	public void setFlag6(String flag6) {
		this.flag6 = flag6;
	}
	public String getFlag7() {
		return flag7;
	}
	public void setFlag7(String flag7) {
		this.flag7 = flag7;
	}
	public String getFlag8() {
		return flag8;
	}
	public void setFlag8(String flag8) {
		this.flag8 = flag8;
	}
	public String getFlag9() {
		return flag9;
	}
	public void setFlag9(String flag9) {
		this.flag9 = flag9;
	}
	public String getFssj() {
		return fssj;
	}
	public void setFssj(String fssj) {
		this.fssj = fssj;
	}
	public String getFxr() {
		return fxr;
	}
	public void setFxr(String fxr) {
		this.fxr = fxr;
	}
	public String getGzqxxx() {
		return gzqxxx;
	}
	public void setGzqxxx(String gzqxxx) {
		this.gzqxxx = gzqxxx;
	}
	public String getHbr() {
		return hbr;
	}
	public void setHbr(String hbr) {
		this.hbr = hbr;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getJhzt() {
		return jhzt;
	}
	public void setJhzt(String jhzt) {
		this.jhzt = jhzt;
	}
	public String getQxr() {
		return qxr;
	}
	public void setQxr(String qxr) {
		this.qxr = qxr;
	}
	public String getSblx() {
		return sblx;
	}
	public void setSblx(String sblx) {
		this.sblx = sblx;
	}
	public String getSbmc() {
		return sbmc;
	}
	public void setSbmc(String sbmc) {
		this.sbmc = sbmc;
	}
	public String getTbr() {
		return tbr;
	}
	public void setTbr(String tbr) {
		this.tbr = tbr;
	}
	public String getTimeid() {
		return timeid;
	}
	public void setTimeid(String timeid) {
		this.timeid = timeid;
	}
	public Integer getTs() {
		return ts;
	}
	public void setTs(Integer ts) {
		this.ts = ts;
	}
	public String getYsr() {
		return ysr;
	}
	public void setYsr(String ysr) {
		this.ysr = ysr;
	}


	
   








}