package com.fuguo.form;

import java.io.Serializable;
import java.util.Date;

import org.apache.struts.action.ActionForm;

import bsw.base.BaseDTO;



/**
 * User generated by MyEclipse - Hibernate Tools
 */

public class UserForm    extends ActionForm  {


    // Fields    

     private Integer id;
     private Integer dwId;
     private String banzu;
     private String xm;
     private String kl;
     private String nx;
     private String wx;
     private String sj;
     private String otherflag;//½ÇÉ«
     private String otherflag2;
     private String datestart;
     private String dateend;




   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getDwId() {
        return this.dwId;
    }
    
    public void setDwId(Integer dwId) {
        this.dwId = dwId;
    }

    public String getBanzu() {
        return this.banzu;
    }
    
    public void setBanzu(String banzu) {
        this.banzu = banzu;
    }

    public String getXm() {
        return this.xm;
    }
    
    public void setXm(String xm) {
        this.xm = xm;
    }

    public String getKl() {
        return this.kl;
    }
    
    public void setKl(String kl) {
        this.kl = kl;
    }

    public String getNx() {
        return this.nx;
    }
    
    public void setNx(String nx) {
        this.nx = nx;
    }

    public String getWx() {
        return this.wx;
    }
    
    public void setWx(String wx) {
        this.wx = wx;
    }

    public String getSj() {
        return this.sj;
    }
    
    public void setSj(String sj) {
        this.sj = sj;
    }

    public String getOtherflag() {
        return this.otherflag;
    }
    
    public void setOtherflag(String otherflag) {
        this.otherflag = otherflag;
    }

    public String getOtherflag2() {
        return this.otherflag2;
    }
    
    public void setOtherflag2(String otherflag2) {
        this.otherflag2 = otherflag2;
    }

	public String getDateend() {
		return dateend;
	}

	public void setDateend(String dateend) {
		this.dateend = dateend;
	}

	public String getDatestart() {
		return datestart;
	}

	public void setDatestart(String datestart) {
		this.datestart = datestart;
	}


	
   








}