package com.fuguo.dto;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;

import bsw.base.BaseDTO;



/**
 * Gpmc generated by MyEclipse - Hibernate Tools
 */

public class GpmcDTO  extends BaseDTO implements Comparable{


    // Fields    

     private String zqdm;
     private String zqmc;
     private String flag1;
     private String flag2;//0基金   1股票 
     private double zgbnum;//以万为单位，避免超大数据的存入；
     private int volflag;
     
     private String oneDateVol;
     private String twoDateVol;
     private String threeDateVol;
     /**
      * 特色选股用到；
      */
     private double scj;//市场价
     private String zgbStr;//总股本
     private String zszStr;//总市值
     
     private String dqyltnumStr;//当前已流通股份；
     private String dqyltszStr;//当前已流通市值；
     
     private String dateLtszStr;//该日期之前流通市值；
     private String dateLtgfNumberStr;//该日期之前流通股份；
     private String dateSxgfNumberStr;//该日期之前受限股份；
     
     private String dateYqjjszStr;//预期解禁市值；
     private String dateLtgfBFBStr;//该日期之前流通股份%；
     
    // private String newFlag;//默认不是新股；
     private int newFlagInt;//新股为1，默认不是新股，为0；
     
     private Map<String,String> jiejinMessageMap = new LinkedHashMap<String,String>();

    // Constructors

   

	

	/** default constructor */
    public GpmcDTO() {
    }

	/** minimal constructor */
    public GpmcDTO(String zqmc) {
        this.zqmc = zqmc;
    }
    
    /** full constructor */
    public GpmcDTO(String zqmc, String flag1, String flag2) {
        this.zqmc = zqmc;
        this.flag1 = flag1;
        this.flag2 = flag2;
    }
    

   
    // Property accessors

    public String getZqdm() {
        return this.zqdm;
    }
    
    public void setZqdm(String zqdm) {
        this.zqdm = zqdm;
    }

    public String getZqmc() {
        return this.zqmc;
    }
    
    public void setZqmc(String zqmc) {
        this.zqmc = zqmc;
    }

    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

	@Override
	public Serializable getId() {
		// TODO 自动生成方法存根
		return this.zqdm;
	}

	@Override
	public void setId(Serializable id) {
		// TODO 自动生成方法存根
		this.zqdm = (String)id;
	}

	public String getDateLtgfBFBStr() {
		return dateLtgfBFBStr;
	}

	public void setDateLtgfBFBStr(String dateLtgfBFBStr) {
		this.dateLtgfBFBStr = dateLtgfBFBStr;
	}

	public String getDateLtgfNumberStr() {
		return dateLtgfNumberStr;
	}

	public void setDateLtgfNumberStr(String dateLtgfNumberStr) {
		this.dateLtgfNumberStr = dateLtgfNumberStr;
	}

	public String getDateLtszStr() {
		return dateLtszStr;
	}

	public void setDateLtszStr(String dateLtszStr) {
		this.dateLtszStr = dateLtszStr;
	}

	public String getDateSxgfNumberStr() {
		return dateSxgfNumberStr;
	}

	public void setDateSxgfNumberStr(String dateSxgfNumberStr) {
		this.dateSxgfNumberStr = dateSxgfNumberStr;
	}

	public double getScj() {
		return scj;
	}

	public void setScj(double scj) {
		this.scj = scj;
	}

	public String getZgbStr() {
		return zgbStr;
	}

	public void setZgbStr(String zgbStr) {
		this.zgbStr = zgbStr;
	}

	public String getZszStr() {
		return zszStr;
	}

	public void setZszStr(String zszStr) {
		this.zszStr = zszStr;
	}

	public String getDqyltnumStr() {
		return dqyltnumStr;
	}

	public void setDqyltnumStr(String dqyltnumStr) {
		this.dqyltnumStr = dqyltnumStr;
	}

	public String getDqyltszStr() {
		return dqyltszStr;
	}

	public void setDqyltszStr(String dqyltszStr) {
		this.dqyltszStr = dqyltszStr;
	}

	public String getDateYqjjszStr() {
		return dateYqjjszStr;
	}

	public void setDateYqjjszStr(String dateYqjjszStr) {
		this.dateYqjjszStr = dateYqjjszStr;
	}

	public double getZgbnum() {
		return zgbnum;
	}

	public void setZgbnum(double zgbnum) {
		this.zgbnum = zgbnum;
	}

//	public String getNewFlag() {
//		return newFlag;
//	}
//
//	public void setNewFlag(String newFlag) {
//		this.newFlag = newFlag;
//	}

	public int compareTo(Object o) {
		 GpmcDTO sdto = (GpmcDTO)o;
	     return this.newFlagInt-sdto.newFlagInt;
	}

	public int getNewFlagInt() {
		return newFlagInt;
	}

	public void setNewFlagInt(int newFlagInt) {
		this.newFlagInt = newFlagInt;
	}

	public int getVolflag() {
		return volflag;
	}

	public void setVolflag(int volflag) {
		this.volflag = volflag;
	}

	public String getOneDateVol() {
		return oneDateVol;
	}

	public void setOneDateVol(String oneDateVol) {
		this.oneDateVol = oneDateVol;
	}

	public String getThreeDateVol() {
		return threeDateVol;
	}

	public void setThreeDateVol(String threeDateVol) {
		this.threeDateVol = threeDateVol;
	}

	public String getTwoDateVol() {
		return twoDateVol;
	}

	public void setTwoDateVol(String twoDateVol) {
		this.twoDateVol = twoDateVol;
	}

	public Map<String, String> getJiejinMessageMap() {
		return jiejinMessageMap;
	}

	public void addJiejinMessageMap(Map<String, String> jiejinMessageMap) {
		this.jiejinMessageMap = jiejinMessageMap;
	}

	
   








}