package com.fuguo.dto;

import java.io.Serializable;

import bsw.base.BaseDTO;



/**
 * Gpyl generated by MyEclipse - Hibernate Tools
 */

public class GpylDTO  extends BaseDTO {


    // Fields    

     private Integer id;
     private String lx;
     private String title;
     private String content;
     private String flag1;//日期
     private String flag2;


    // Constructors

    /** default constructor */
    public GpylDTO() {
    }

    
    /** full constructor */
    public GpylDTO(String lx, String title, String content, String flag1, String flag2) {
        this.lx = lx;
        this.title = title;
        this.content = content;
        this.flag1 = flag1;
        this.flag2 = flag2;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getLx() {
        return this.lx;
    }
    
    public void setLx(String lx) {
        this.lx = lx;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
   

    @Override
	public void setId(Serializable id) {
		// TODO 自动生成方法存根
		this.id = (Integer)id;
		
	}






}