package com.fuguo.dto;

import java.io.Serializable;

import bsw.base.BaseDTO;



/**
 * Juesefunction generated by MyEclipse - Hibernate Tools
 */

public class JuesefunctionDTO  extends BaseDTO  {


    // Fields    

     private Integer id;
     private String juesename;
     private String functioncode;
     private String otherflag;


    // Constructors

    /** default constructor */
    public JuesefunctionDTO() {
    }

    
    /** full constructor */
    public JuesefunctionDTO(String juesename, String functioncode, String otherflag) {
        this.juesename = juesename;
        this.functioncode = functioncode;
        this.otherflag = otherflag;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getJuesename() {
        return this.juesename;
    }
    
    public void setJuesename(String juesename) {
        this.juesename = juesename;
    }

    public String getFunctioncode() {
        return this.functioncode;
    }
    
    public void setFunctioncode(String functioncode) {
        this.functioncode = functioncode;
    }

    public String getOtherflag() {
        return this.otherflag;
    }
    
    public void setOtherflag(String otherflag) {
        this.otherflag = otherflag;
    }


    @Override
	public void setId(Serializable id) {
		this.id=(Integer)id;
		
	}
   








}