package com.fuguo.dto;

import java.io.Serializable;
import java.util.Date;

import bsw.base.BaseDTO;


/**
 * Lsjg generated by MyEclipse - Hibernate Tools
 */

public class KxianDTO   {


    // Fields    

     
     private Date date;
     private String day;
     
     private double open;
     private double high;
     private double low;
     private double close;
     private double volume;
     private double adjclose;//∏¥»®º€”√£ª
    


    // Constructors

    /** default constructor */
    public KxianDTO() {
    }



	public double getAdjclose() {
		return adjclose;
	}



	public void setAdjclose(double adjclose) {
		this.adjclose = adjclose;
	}



	public double getClose() {
		return close;
	}



	public void setClose(double close) {
		this.close = close;
	}



	public Date getDate() {
		return date;
	}



	public void setDate(Date date) {
		this.date = date;
	}



	public double getHigh() {
		return high;
	}



	public void setHigh(double high) {
		this.high = high;
	}



	public double getLow() {
		return low;
	}



	public void setLow(double low) {
		this.low = low;
	}



	public double getOpen() {
		return open;
	}



	public void setOpen(double open) {
		this.open = open;
	}



	public double getVolume() {
		return volume;
	}



	public void setVolume(double volume) {
		this.volume = volume;
	}



	public String getDay() {
		return day;
	}



	public void setDay(String day) {
		this.day = day;
	}

    
  





}