package com.fuguo.dto;

import java.io.Serializable;
import java.util.Date;

import bsw.base.BaseDTO;


/**
 * Lsjg generated by MyEclipse - Hibernate Tools
 */

public class LsjgDTO  extends BaseDTO {


    // Fields    

     private Integer id;
     private String zqdm;
     private String zqmc;
     private Date date;
     private double open;
     private double high;
     private double low;
     private double close;
     private double volume;
     private double adjclose;//复权价用；
     private double fqyz;//复权因子；
     private String flag1;
     private String flag2;


    // Constructors

    /** default constructor */
    public LsjgDTO() {
    }

    
    /** full constructor */
    public LsjgDTO(String zqdm, String zqmc, Date date, double open, double high, double low, double close, double volume, double adjclose, String flag1, String flag2) {
        this.zqdm = zqdm;
        this.zqmc = zqmc;
        this.date = date;
        this.open = open;
        this.high = high;
        this.low = low;
        this.close = close;
        this.volume = volume;
        this.adjclose = adjclose;
        this.flag1 = flag1;
        this.flag2 = flag2;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getZqdm() {
        return this.zqdm;
    }
    
    public void setZqdm(String zqdm) {
        this.zqdm = zqdm;
    }

    public String getZqmc() {
        return this.zqmc;
    }
    
    public void setZqmc(String zqmc) {
        this.zqmc = zqmc;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public double getOpen() {
        return this.open;
    }
    
    public void setOpen(double open) {
        this.open = open;
    }

    public double getHigh() {
        return this.high;
    }
    
    public void setHigh(double high) {
        this.high = high;
    }

    public double getLow() {
        return this.low;
    }
    
    public void setLow(double low) {
        this.low = low;
    }

    public double getClose() {
        return this.close;
    }
    
    public void setClose(double close) {
        this.close = close;
    }

    public double getVolume() {
        return this.volume;
    }
    
    public void setVolume(double volume) {
        this.volume = volume;
    }

    public double getAdjclose() {
        return this.adjclose;
    }
    
    public void setAdjclose(double adjclose) {
        this.adjclose = adjclose;
    }

    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
   

    @Override
	public void setId(Serializable id) {
		// TODO 自动生成方法存根
		this.id = (Integer)id;
		
	}


	public double getFqyz() {
		return fqyz;
	}


	public void setFqyz(double fqyz) {
		this.fqyz = fqyz;
	}






}