package com.fuguo.dto;

import java.io.Serializable;
import java.util.Date;

import bsw.base.BaseDTO;


/**
 * Lsjgdate generated by MyEclipse - Hibernate Tools
 */

public class LsjgdateDTO   extends BaseDTO {


    // Fields    

     private String zqdm;
     private String zqmc;
     private Date datestart;
     private Date date;
     private String flag1;
     private String flag2;


    // Constructors

    /** default constructor */
    public LsjgdateDTO() {
    }

    
    /** full constructor */
    public LsjgdateDTO(Date date, String flag1, String flag2) {
        this.date = date;
        this.flag1 = flag1;
        this.flag2 = flag2;
    }
    

   
    // Property accessors

    public String getZqdm() {
        return this.zqdm;
    }
    
    public void setZqdm(String zqdm) {
        this.zqdm = zqdm;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
   
    @Override
	public Serializable getId() {
		// TODO 自动生成方法存根
		return this.zqdm;
	}

	@Override
	public void setId(Serializable id) {
		// TODO 自动生成方法存根
		this.zqdm = (String)id;
	}


	public Date getDatestart() {
		return datestart;
	}


	public void setDatestart(Date datestart) {
		this.datestart = datestart;
	}


	public String getZqmc() {
		return zqmc;
	}


	public void setZqmc(String zqmc) {
		this.zqmc = zqmc;
	}







}