package com.fuguo.dto;

import java.io.Serializable;
import java.util.Date;

import bsw.base.BaseDTO;



/**
 * Gpmc generated by MyEclipse - Hibernate Tools
 */

public class MygpmcDTO  extends BaseDTO {


    // Fields    
	private Integer id;
     private String zqdm;
     private String zqmc;
     private String flag1;
     private String flag2;
     private double scj;//市场价
     
     private Date datestart;
     private Date date;
     
     

    // Constructors

    public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getDatestart() {
		return datestart;
	}

	public void setDatestart(Date datestart) {
		this.datestart = datestart;
	}

	public double getScj() {
		return scj;
	}

	public void setScj(double scj) {
		this.scj = scj;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/** default constructor */
    public MygpmcDTO() {
    }

	/** minimal constructor */
    public MygpmcDTO(String zqmc) {
        this.zqmc = zqmc;
    }
    
    /** full constructor */
    public MygpmcDTO(String zqmc, String flag1, String flag2) {
        this.zqmc = zqmc;
        this.flag1 = flag1;
        this.flag2 = flag2;
    }
    

   
    // Property accessors

    public String getZqdm() {
        return this.zqdm;
    }
    
    public void setZqdm(String zqdm) {
        this.zqdm = zqdm;
    }

    public String getZqmc() {
        return this.zqmc;
    }
    
    public void setZqmc(String zqmc) {
        this.zqmc = zqmc;
    }

    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

	@Override
	public Serializable getId() {
		// TODO 自动生成方法存根
		return this.id;
	}

	@Override
	public void setId(Serializable id) {
		// TODO 自动生成方法存根
		this.id = (Integer)id;
	}
   








}