package com.fuguo.dto;

import java.io.Serializable;
import java.util.Date;

import bsw.base.BaseDTO;


/**
 * Gzqx generated by MyEclipse - Hibernate Tools
 */

public class SunDTO   extends BaseDTO{


    // Fields    

     private Integer id;
     private String timeid;
     private String bdz;
     private String sblx;
     private String sbmc;
     private String dydj;
     private String gzqxxx;
     private String clgc;
     private Date fssj;
     private Date clsj;
     private String fssjStr;
     private String clsjStr;
     private Integer ts;
     private String fxr;
     private String hbr;
     private String qxr;
     private String ysr;
     private String tbr;
     private String banzu;
     private String bz;
     private String jhzt;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private String flag6;
     private String flag7;
     private String flag8;
     private String flag9;
     private String flag10;
     
     private String fileName;


    // Constructors

    public String getFileName() {
		return fileName;
	}


	public void setFileName(String fileName) {
		this.fileName = fileName;
	}


	/** default constructor */
    public SunDTO() {
    }

    
    /** full constructor */
    public SunDTO(String timeid, String bdz, String sblx, String sbmc, String dydj, String gzqxxx, String clgc, Date fssj, Date clsj, Integer ts, String fxr, String hbr, String qxr, String ysr, String tbr, String banzu, String bz, String jhzt, String flag1, String flag2, String flag3, String flag4, String flag5, String flag6, String flag7, String flag8, String flag9, String flag10) {
        this.timeid = timeid;
        this.bdz = bdz;
        this.sblx = sblx;
        this.sbmc = sbmc;
        this.dydj = dydj;
        this.gzqxxx = gzqxxx;
        this.clgc = clgc;
        this.fssj = fssj;
        this.clsj = clsj;
        this.ts = ts;
        this.fxr = fxr;
        this.hbr = hbr;
        this.qxr = qxr;
        this.ysr = ysr;
        this.tbr = tbr;
        this.banzu = banzu;
        this.bz = bz;
        this.jhzt = jhzt;
        this.flag1 = flag1;
        this.flag2 = flag2;
        this.flag3 = flag3;
        this.flag4 = flag4;
        this.flag5 = flag5;
        this.flag6 = flag6;
        this.flag7 = flag7;
        this.flag8 = flag8;
        this.flag9 = flag9;
        this.flag10 = flag10;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getTimeid() {
        return this.timeid;
    }
    
    public void setTimeid(String timeid) {
        this.timeid = timeid;
    }

    public String getBdz() {
        return this.bdz;
    }
    
    public void setBdz(String bdz) {
        this.bdz = bdz;
    }

    public String getSblx() {
        return this.sblx;
    }
    
    public void setSblx(String sblx) {
        this.sblx = sblx;
    }

    public String getSbmc() {
        return this.sbmc;
    }
    
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc;
    }

    public String getDydj() {
        return this.dydj;
    }
    
    public void setDydj(String dydj) {
        this.dydj = dydj;
    }

    public String getGzqxxx() {
        return this.gzqxxx;
    }
    
    public void setGzqxxx(String gzqxxx) {
        this.gzqxxx = gzqxxx;
    }

    public String getClgc() {
        return this.clgc;
    }
    
    public void setClgc(String clgc) {
        this.clgc = clgc;
    }

    public Date getFssj() {
        return this.fssj;
    }
    
    public void setFssj(Date fssj) {
        this.fssj = fssj;
    }

    public Date getClsj() {
        return this.clsj;
    }
    
    public void setClsj(Date clsj) {
        this.clsj = clsj;
    }

    public Integer getTs() {
        return this.ts;
    }
    
    public void setTs(Integer ts) {
        this.ts = ts;
    }

    public String getFxr() {
        return this.fxr;
    }
    
    public void setFxr(String fxr) {
        this.fxr = fxr;
    }

    public String getHbr() {
        return this.hbr;
    }
    
    public void setHbr(String hbr) {
        this.hbr = hbr;
    }

    public String getQxr() {
        return this.qxr;
    }
    
    public void setQxr(String qxr) {
        this.qxr = qxr;
    }

    public String getYsr() {
        return this.ysr;
    }
    
    public void setYsr(String ysr) {
        this.ysr = ysr;
    }

    public String getTbr() {
        return this.tbr;
    }
    
    public void setTbr(String tbr) {
        this.tbr = tbr;
    }

    public String getBanzu() {
        return this.banzu;
    }
    
    public void setBanzu(String banzu) {
        this.banzu = banzu;
    }

    public String getBz() {
        return this.bz;
    }
    
    public void setBz(String bz) {
        this.bz = bz;
    }

    public String getJhzt() {
        return this.jhzt;
    }
    
    public void setJhzt(String jhzt) {
        this.jhzt = jhzt;
    }

    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }

    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }

    public String getFlag6() {
        return this.flag6;
    }
    
    public void setFlag6(String flag6) {
        this.flag6 = flag6;
    }

    public String getFlag7() {
        return this.flag7;
    }
    
    public void setFlag7(String flag7) {
        this.flag7 = flag7;
    }

    public String getFlag8() {
        return this.flag8;
    }
    
    public void setFlag8(String flag8) {
        this.flag8 = flag8;
    }

    public String getFlag9() {
        return this.flag9;
    }
    
    public void setFlag9(String flag9) {
        this.flag9 = flag9;
    }

    public String getFlag10() {
        return this.flag10;
    }
    
    public void setFlag10(String flag10) {
        this.flag10 = flag10;
    }
   
    @Override
	public void setId(Serializable id) {
		// TODO 自动生成方法存根
		this.id = (Integer)id;
	}


	public String getClsjStr() {
		return clsjStr;
	}


	public void setClsjStr(String clsjStr) {
		this.clsjStr = clsjStr;
	}


	public String getFssjStr() {
		return fssjStr;
	}


	public void setFssjStr(String fssjStr) {
		this.fssjStr = fssjStr;
	}







}