package com.fuguo.dto;

import java.io.Serializable;

import bsw.base.BaseDTO;



/**
 * Systemconfig generated by MyEclipse - Hibernate Tools
 */

public class SystemconfigDTO  extends BaseDTO {


    // Fields    

     private String functioncode;
     private String functionname;
     private String functionvalue;
     private String flag1;
     private String flag2;


    // Constructors

    /** default constructor */
    public SystemconfigDTO() {
    }

    
    /** full constructor */
    public SystemconfigDTO(String functionname, String functionvalue, String flag1, String flag2) {
        this.functionname = functionname;
        this.functionvalue = functionvalue;
        this.flag1 = flag1;
        this.flag2 = flag2;
    }
    

   
    // Property accessors

    public String getFunctioncode() {
        return this.functioncode;
    }
    
    public void setFunctioncode(String functioncode) {
        this.functioncode = functioncode;
    }

    public String getFunctionname() {
        return this.functionname;
    }
    
    public void setFunctionname(String functionname) {
        this.functionname = functionname;
    }

    public String getFunctionvalue() {
        return this.functionvalue;
    }
    
    public void setFunctionvalue(String functionvalue) {
        this.functionvalue = functionvalue;
    }

    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }


	


    @Override
	public void setId(Serializable id) {
		// TODO 自动生成方法存根
		this.functioncode = (String)id;
		
	}


	@Override
	public Serializable getId() {
		// TODO 自动生成方法存根
		return this.functioncode;
	}
   








}