package com.fuguo.dto;

import java.io.Serializable;
import java.util.Date;

import bsw.base.BaseDTO;



/**
 * User generated by MyEclipse - Hibernate Tools
 */

public class UserDTO    extends BaseDTO  {


    // Fields    

     private Integer id;
     private Integer dwId;
     private String dwname;//自己添加的。不关联数据库。
     private String banzu;
     private String xm;
     private String kl;
     private String nx;//资金账号
     private String wx;//客户代码
     private String sj;
     private String otherflag;
     private String otherflag2;
     private Date datestart;
     private Date dateend;


    // Constructors

    /** default constructor */
    public UserDTO() {
    }

    
    /** full constructor */
    public UserDTO(Integer dwId, String banzu, String xm, String kl, String nx, String wx, String sj, String otherflag, String otherflag2) {
        this.dwId = dwId;
        this.banzu = banzu;
        this.xm = xm;
        this.kl = kl;
        this.nx = nx;
        this.wx = wx;
        this.sj = sj;
        this.otherflag = otherflag;
        this.otherflag2 = otherflag2;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getDwId() {
        return this.dwId;
    }
    
    public void setDwId(Integer dwId) {
        this.dwId = dwId;
    }

    public String getBanzu() {
        return this.banzu;
    }
    
    public void setBanzu(String banzu) {
        this.banzu = banzu;
    }

    public String getXm() {
        return this.xm;
    }
    
    public void setXm(String xm) {
        this.xm = xm;
    }

    public String getKl() {
        return this.kl;
    }
    
    public void setKl(String kl) {
        this.kl = kl;
    }

    public String getNx() {
        return this.nx;
    }
    
    public void setNx(String nx) {
        this.nx = nx;
    }

    public String getWx() {
        return this.wx;
    }
    
    public void setWx(String wx) {
        this.wx = wx;
    }

    public String getSj() {
        return this.sj;
    }
    
    public void setSj(String sj) {
        this.sj = sj;
    }

    public String getOtherflag() {
        return this.otherflag;
    }
    
    public void setOtherflag(String otherflag) {
        this.otherflag = otherflag;
    }

    public String getOtherflag2() {
        return this.otherflag2;
    }
    
    public void setOtherflag2(String otherflag2) {
        this.otherflag2 = otherflag2;
    }


	@Override
	public void setId(Serializable id) {
		// TODO 自动生成方法存根
		this.id=(Integer)id;
	}


	public String getDwname() {
		return dwname;
	}


	public void setDwname(String dwname) {
		this.dwname = dwname;
	}


	public Date getDateend() {
		return dateend;
	}


	public void setDateend(Date dateend) {
		this.dateend = dateend;
	}


	public Date getDatestart() {
		return datestart;
	}


	public void setDatestart(Date datestart) {
		this.datestart = datestart;
	}
   








}